Implement Greetings Display with Message From Rails Api
gisachris/hello-rails-front-end pull request #1
Opened 2023-09-27 13:59 UTC by gisachris

## IN This PR I present the Implementation of Greetings Display From Rails Api 📡 :
Below are some of my implementations in this PR🤝 .

## Requirements
- Use git-flow 🌊.
- Create a new React app
- Create the App component with react-router.
- Create the `Greeting` component that will display a `greeting`. Set it up as a `route` in your `App` component.
- Create a `store`, an `action` and a `reducer` that will connect to you `API` endpont to get the random `greeting`.
- Display the random greeting in your `Greeting` component.

## ACHIEVEMENTS ⛰️
- Use git-flow 🌊. ✅ 
- Create a new React app. ✅ 
- Create the App component with react-router. ✅ 
- Create the `Greeting` component that will display a `greeting`. Set it up as a `route` in your `App` component. ✅ 
- Create a `store`, an `action` and a `reducer` that will connect to you `API` endpont to get the random `greeting`. ✅ 
- Display the random greeting in your `Greeting` component. ✅ 

## Conclusion
**I look forward to hearing 👂 from you The CR in terms of what can be better implemented 👨‍💻 for the project.**

Thankyou!. 🙇

2023-09-27 15:02 UTC, elisha2kyakpo1 requested changes
Hi 👋 @gisachris, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description are good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.
👏 The API is nicely set up.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-27 15:02 UTC, elisha2kyakpo1 commented on src/components/message.js
> +    </div>
- [ ] Kindly troubleshoot and find out why the app can't display messages from the API. I can see some pieces of code that should be done under redux being implemented here.

![messages](https://github.com/gisachris/hello-rails-front-end/assets/53124548/e0389306-34e6-4f53-aa42-ae02cc4e1168)

2023-09-28 03:14 UTC, gisachris commented
## IN This PR I Implemented Required Changes ♻️ :
Below are some of my implementations in this PR🤝 .

## Required Change ♻️ 
- Move fetching Functionality away from the component(`message.js`)
- Add page navigation

## ACHIEVEMENTS ⛰️
- Move fetching Functionality away from the component(`message.js`) ✅ 
- Add page navigation. ✅ 

![Capture](https://github.com/gisachris/hello-rails-front-end/assets/125574259/31687b45-0f11-423e-88c6-72de018b0b7a)

## Conclusion
**I look forward to hearing 👂 from you The CR in terms of what can be better implemented 👨‍💻 for the project.**

Thankyou!. 🙇

2023-09-28 03:36 UTC, Davidosky007 approved these changes
Hi @gisachris 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* API works as expected 👍 
* Well-written PR 👍 
* Good looking readme 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 03:39 UTC, merged